name: Deploy Firebase Rules

on:
  push:
    branches:
      - master
    paths:
      - '**.rules'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set CORS
        run: gsutil cors set cors.json gs://epimtheusproject.appspot.com

      - name: Deploy Firestore
        run: firebase deploy --only firestore --project=epimtheusproject

      - name: Deploy Storage
        run: firebase deploy --only storage --project=epimtheusproject